"""kNN cascade post-processing for low-confidence predictions.

When a prediction's confidence falls below the cascade threshold, replace it
with the nearest-neighbor label from the embedding space. This helps rare
cancer types that lack sufficient training signal for the supervised model.
"""

import csv
from pathlib import Path

import numpy as np


def _load_labels_meta(labels_csv_path: str) -> list[dict]:
    """Load label metadata, handling BOM and title row."""
    with open(labels_csv_path, encoding="utf-8-sig") as f:
        lines = f.readlines()
    header_idx = 0
    for i, line in enumerate(lines):
        if "Term" in line and "Group" in line:
            header_idx = i
            break
    reader = csv.DictReader(lines[header_idx:])
    meta = []
    for row in reader:
        term = row.get("Term", "").strip()
        group = row.get("Group", "").strip()
        code = row.get("Vet-ICD-O-canine-1 code", "").strip()
        if term and group:
            meta.append({"term": term, "group": group, "code": code})
    return meta


def _knn_lookup(
    report_embeddings: np.ndarray,
    label_embeddings: np.ndarray,
    labels_meta: list[dict],
    case_ids: list[str],
    k: int,
) -> dict[str, dict]:
    """Build case_id → kNN prediction mapping."""
    min_n = min(len(labels_meta), label_embeddings.shape[0])
    labels_meta = labels_meta[:min_n]
    label_embs = label_embeddings[:min_n]

    r_norms = np.linalg.norm(report_embeddings, axis=1, keepdims=True).clip(1e-9)
    l_norms = np.linalg.norm(label_embs, axis=1, keepdims=True).clip(1e-9)
    r_unit = report_embeddings / r_norms
    l_unit = label_embs / l_norms

    lookup: dict[str, dict] = {}
    chunk_size = 512
    for start in range(0, len(case_ids), chunk_size):
        end = min(len(case_ids), start + chunk_size)
        sims = r_unit[start:end] @ l_unit.T
        topk_idx = np.argpartition(-sims, kth=min(k, sims.shape[1] - 1), axis=1)[:, :k]

        for i in range(end - start):
            top_i = topk_idx[i]
            top_sims = sims[i, top_i]
            order = np.argsort(-top_sims)
            top_i = top_i[order]
            top_sims = top_sims[order]

            group_votes: dict[str, float] = {}
            for idx, s in zip(top_i, top_sims):
                g = labels_meta[int(idx)]["group"]
                group_votes[g] = group_votes.get(g, 0.0) + float(s)
            best_group = max(group_votes, key=lambda g: group_votes[g])

            for idx, s in zip(top_i, top_sims):
                if labels_meta[int(idx)]["group"] == best_group:
                    meta = labels_meta[int(idx)]
                    lookup[case_ids[start + i]] = {
                        "predicted_term": meta["term"],
                        "predicted_group": meta["group"],
                        "predicted_code": meta["code"],
                        "confidence": f"{float(s):.2f}",
                        "method": "knn_fallback",
                    }
                    break

    return lookup


def _load_adaptive_thresholds(path: str) -> dict[str, float] | None:
    """Load per-group thresholds from JSON, or None if not found."""
    p = Path(path)
    if not p.exists():
        return None
    import json
    with open(p) as f:
        return json.load(f)


# Default path for adaptive thresholds (generated by threshold tuning)
ADAPTIVE_THRESHOLDS_PATH = "ml/output/evaluation/adaptive_thresholds.json"


def apply_cascade(
    predictions_csv: str,
    report_embeddings: np.ndarray,
    label_embeddings: np.ndarray,
    case_ids: list[str],
    labels_csv_path: str,
    threshold: float,
    k: int = 5,
    adaptive_thresholds_path: str = "",
) -> None:
    """Replace low-confidence predictions in-place with kNN results.

    When adaptive_thresholds_path is set, each group uses its own optimized
    threshold.  Otherwise falls back to the global threshold.
    """
    labels_meta = _load_labels_meta(labels_csv_path)
    lookup = _knn_lookup(report_embeddings, label_embeddings, labels_meta, case_ids, k)

    adaptive = None
    if adaptive_thresholds_path:
        adaptive = _load_adaptive_thresholds(adaptive_thresholds_path)
        if adaptive:
            print(f"Cascade: using adaptive per-group thresholds from {adaptive_thresholds_path}")

    # Read existing predictions
    with open(predictions_csv, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
        fieldnames = list(rows[0].keys()) if rows else []

    n_replaced = 0
    for row in rows:
        if row["predicted_term"] == "Uncategorized":
            continue
        conf = float(row.get("confidence", 0))
        group = row.get("predicted_group", "")
        t = adaptive.get(group, threshold) if adaptive else threshold
        if t > 0 and conf < t:
            cid = row["case_id"]
            if cid in lookup:
                knn = lookup[cid]
                row["predicted_term"] = knn["predicted_term"]
                row["predicted_group"] = knn["predicted_group"]
                row["predicted_code"] = knn["predicted_code"]
                row["confidence"] = knn["confidence"]
                row["method"] = knn["method"]
                n_replaced += 1

    # Write back
    with open(predictions_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    mode = "adaptive" if adaptive else f"global t={threshold}"
    print(f"Cascade: replaced {n_replaced} predictions with kNN ({mode})")
