-- CalEnviroScreen 4.0 county-level aggregated environmental health data
CREATE TABLE IF NOT EXISTS calenviroscreen (
    id SERIAL PRIMARY KEY,
    county_id INTEGER NOT NULL REFERENCES counties(id),
    ces_score NUMERIC(6,2),
    pollution_burden NUMERIC(6,2),
    ozone NUMERIC(6,2),
    pm25 NUMERIC(6,2),
    diesel_pm NUMERIC(6,2),
    pesticides NUMERIC(6,2),
    toxic_releases NUMERIC(6,2),
    traffic NUMERIC(6,2),
    drinking_water NUMERIC(6,2),
    lead NUMERIC(6,2),
    cleanup_sites NUMERIC(6,2),
    groundwater_threats NUMERIC(6,2),
    hazardous_waste NUMERIC(6,2),
    solid_waste NUMERIC(6,2),
    impaired_water NUMERIC(6,2),
    pop_characteristics NUMERIC(6,2),
    asthma NUMERIC(6,2),
    low_birth_weight NUMERIC(6,2),
    cardiovascular NUMERIC(6,2),
    poverty NUMERIC(6,2),
    unemployment NUMERIC(6,2),
    housing_burden NUMERIC(6,2),
    education NUMERIC(6,2),
    linguistic_isolation NUMERIC(6,2),
    UNIQUE(county_id)
);
