#!/bin/sh
# One-shot provisioning against Floci's AWS API emulation (:4566): creates
# the RDS Postgres instance and Cognito user pool/client (reusing them if
# they already exist), then writes the resulting connection info to a
# shared volume for other services to source.
#
# Always re-resolves and rewrites $OUT, even when the RDS instance/Cognito
# pool already exist — Floci's own container gets a new docker-network IP
# every time it restarts (e.g. `docker compose down && up`, even without
# `-v`), so a cached DATABASE_URL from a previous run can silently point at
# a dead IP. The RDS instance identifier / Cognito pool name stay stable
# across restarts; the IP behind them does not.
#
# THROWAWAY: this hand-rolled aws-cli script is a bridge to unblock local
# dev now. Once the planned CDK project exists, RDS/Cognito provisioning
# for both Floci and real AWS should come from that stack instead, and this
# script should be deleted. See docs/floci-local-dev-migration.md.
set -e

OUT=/shared/floci-outputs.env
DB_ID=vmth-cancer-postgres
DB_NAME=postgres
DB_USER=postgres
DB_PASS=postgres
POOL_NAME=vmth-cancer-registry
CLIENT_NAME=vmth-cancer-registry-web

# No compose healthcheck for floci (its documented /_floci/health endpoint
# turned out to not exist in the version we're on) — poll with the aws cli
# itself instead of assuming the container is ready just because it started.
echo "floci-init: waiting for floci to accept requests..."
until aws sts get-caller-identity > /dev/null 2>&1; do
  sleep 2
done

if aws rds describe-db-instances --db-instance-identifier "$DB_ID" > /dev/null 2>&1; then
  echo "floci-init: RDS instance $DB_ID already exists, reusing"
else
  echo "floci-init: creating RDS Postgres instance ($DB_ID)..."
  # Engine version 18, not prod's 16: Alpine 3.24 (what Floci's postgres:16-
  # alpine and postgres:18-alpine images are both built on) only ships a
  # postgis apk package linked against postgresql18 — there's no pg16-targeted
  # build to install. See install-postgis.sh and docs/floci-local-dev-migration.md.
  aws rds create-db-instance \
    --db-instance-identifier "$DB_ID" \
    --engine postgres \
    --engine-version 18 \
    --db-instance-class db.t3.micro \
    --allocated-storage 20 \
    --master-username "$DB_USER" \
    --master-user-password "$DB_PASS" \
    --db-name "$DB_NAME" \
    > /dev/null
fi

echo "floci-init: waiting for $DB_ID to become available..."
until aws rds describe-db-instances --db-instance-identifier "$DB_ID" \
    --query 'DBInstances[0].DBInstanceStatus' --output text 2>/dev/null | grep -q available; do
  sleep 2
done

DB_HOST=$(aws rds describe-db-instances --db-instance-identifier "$DB_ID" \
  --query 'DBInstances[0].Endpoint.Address' --output text)
DB_PORT=$(aws rds describe-db-instances --db-instance-identifier "$DB_ID" \
  --query 'DBInstances[0].Endpoint.Port' --output text)
echo "floci-init: RDS endpoint is ${DB_HOST}:${DB_PORT}"

POOL_ID=$(aws cognito-idp list-user-pools --max-results 60 \
  --query "UserPools[?Name=='${POOL_NAME}'].Id | [0]" --output text)
if [ -z "$POOL_ID" ] || [ "$POOL_ID" = "None" ]; then
  echo "floci-init: creating Cognito user pool ($POOL_NAME)..."
  POOL_ID=$(aws cognito-idp create-user-pool --pool-name "$POOL_NAME" \
    --query 'UserPool.Id' --output text)
else
  echo "floci-init: Cognito user pool $POOL_NAME already exists ($POOL_ID), reusing"
fi

CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id "$POOL_ID" --max-results 60 \
  --query "UserPoolClients[?ClientName=='${CLIENT_NAME}'].ClientId | [0]" --output text)
if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" = "None" ]; then
  echo "floci-init: creating Cognito app client ($CLIENT_NAME)..."
  CLIENT_ID=$(aws cognito-idp create-user-pool-client \
    --user-pool-id "$POOL_ID" \
    --client-name "$CLIENT_NAME" \
    --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \
    --query 'UserPoolClient.ClientId' --output text)
else
  echo "floci-init: Cognito app client $CLIENT_NAME already exists ($CLIENT_ID), reusing"
fi
echo "floci-init: Cognito pool $POOL_ID / client $CLIENT_ID"

cat > "$OUT" <<EOF
# Generated by floci-init.sh — overrides the static defaults in .env for
# services that source this file. Refreshed on every run (see script
# comment above for why caching would be unsafe).
export DATABASE_URL="postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
export DATABASE_URL_SYNC="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
export FLOCI_DB_HOST="${DB_HOST}"
export FLOCI_DB_PORT="${DB_PORT}"
export FLOCI_DB_ID="${DB_ID}"
export COGNITO_USER_POOL_ID="${POOL_ID}"
export COGNITO_CLIENT_ID="${CLIENT_ID}"
export VITE_COGNITO_USER_POOL_ID="${POOL_ID}"
export VITE_COGNITO_CLIENT_ID="${CLIENT_ID}"
EOF

echo "floci-init: wrote $OUT"
